### ISSUE TITLE
Endpoint richiesta KeyId errato

### ISSUE THREAD

**Issue by digitarenet** [diegosilvestri/SatispayApiIntegration#1]
Credo che l'endpoint per la richiesta del KeyId non sia corretto.
La riga 37 di _AuthenticationSatispayClient.cs_ dovrebbe essere così:

`var result = await Client.PostAsJsonAsync("v1/authentication_keys", request, cancellationToken);`

Almeno per come sono definiti i path nei file Costant.cs

**Comment by diegosilvestri** [comment]
Ciao,
hai ragione. Non lo avevo più aggiornato.
Grazie
Diego
________________________________
Da: Andrea ***@***.***>
Inviato: sabato 22 aprile 2023 22:38
A: diegosilvestri/SatispayApiIntegration ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [diegosilvestri/SatispayApiIntegration] Endpoint richiesta KeyId errato (Issue #1)


Credo che l'endpoint per la richiesta del KeyId non sia corretto.
La riga 37 di AuthenticationSatispayClient.cs dovrebbe essere così:

var result = await Client.PostAsJsonAsync("v1/authentication_keys", request, cancellationToken);

Almeno per come sono definiti i path nei file Costant.cs

**Comment by diegosilvestri** [comment]
Fix
